using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using Calibrator.WpfControl.Abstract;
using Calibrator.WpfControl.Attributes;
using Calibrator.WpfControl.Controls.ScSmartTable.Models;
using Calibrator.WpfControl.Controls.UniTable;
using Calibrator.WpfControl.Sandbox.Models;
using CommunityToolkit.Mvvm.ComponentModel;
using MahApps.Metro.IconPacks;

namespace Calibrator.WpfControl.Sandbox.ViewModels;

public partial class DataLoadingDemoViewModel : BaseViewModel
{
    [ObservableProperty]
    private ObservableCollection<PersonModel> _employees = new();

    [ObservableProperty]
    private int _totalRecords;

    [ObservableProperty]
    private DateTime? _lastLoadTime;

    public DataLoadingDemoViewModel()
    {
        InitializeColumns();
        InitializeTableOperations();
    }

    /// <summary>
    /// Initializes the view model by loading data.
    /// Uses the WithLoading wrapper to automatically manage IsLoading state.
    /// </summary>
    public override async Task InitializeAsync()
    {
        // Load data on initialization using the generated wrapper
        await LoadDataAsync();
    }

    public List<UniTableColumn> Columns { get; set; } = new();
    public List<UniTableBaseAction> TableOperations { get; set; } = new();

    /// <summary>
    /// Loads employee data with a simulated 3-second delay.
    /// Command and wrapper are auto-generated by [RelayCommandWithLoading].
    /// </summary>
    [WithLoading] // Generates body that calls InitializeDataCoreAsync()
    private partial Task LoadDataAsync();

    ///// <summary>
    ///// Core initialization logic - loads initial data.
    ///// </summary>
    //private async Task InitializeDataCoreAsync()
    //{
    //    await LoadDataAsync();
    //}

    /// <summary>
    /// Loads employee data with a simulated 3-second delay.
    /// Command and wrapper are auto-generated by [RelayCommandWithLoading].
    /// </summary>
    [RelayCommandWithLoading] // Generates LoadDataCommand and wrapper
    private async Task LoadDataCoreAsync()
    {
        // Clear existing data
        Employees.Clear();
        TotalRecords = 0;

        // Simulate network delay - loading data from API
        await Task.Delay(3000);

        // Generate sample employee data
        var employees = GenerateSampleEmployees();
        
        foreach (var employee in employees)
        {
            Employees.Add(employee);
        }

        TotalRecords = Employees.Count;
        LastLoadTime = DateTime.Now;
    }

    /// <summary>
    /// Refreshes the data - reloads everything.
    /// Command and wrapper are auto-generated by [RelayCommandWithLoading].
    /// </summary>
    [RelayCommandWithLoading] // Generates RefreshDataCommand and wrapper
    private async Task RefreshDataAsync()
    {
        await LoadDataCoreAsync();
    }

    private List<PersonModel> GenerateSampleEmployees()
    {
        var random = new Random();
        var cities = new[] { "New York", "London", "Paris", "Tokyo", "Berlin", "Madrid", "Rome", "Seoul", "Sydney", "Toronto" };
        var departments = new[] { "Engineering", "Sales", "Marketing", "HR", "Finance", "Operations", "IT", "Legal" };
        var firstNames = new[] { "John", "Jane", "Bob", "Alice", "Charlie", "Diana", "Frank", "Grace", "Henry", "Ivy", "Jack", "Kate", "Leo", "Mary", "Nick", "Olivia", "Paul", "Quinn", "Rose", "Sam" };
        var lastNames = new[] { "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin" };

        var employees = new List<PersonModel>();

        for (int i = 1; i <= 50; i++)
        {
            var firstName = firstNames[random.Next(firstNames.Length)];
            var lastName = lastNames[random.Next(lastNames.Length)];
            var email = $"{firstName.ToLower()}.{lastName.ToLower()}@company.com";
            
            employees.Add(new PersonModel
            {
                Id = i,
                Name = $"{firstName} {lastName}",
                Age = random.Next(22, 65),
                Email = email,
                City = cities[random.Next(cities.Length)],
                IsActive = random.Next(100) > 20, // 80% active
                Salary = random.Next(40000, 150000),
                HireDate = DateTime.Now.AddDays(-random.Next(1, 3650)), // Hired within last 10 years
                Department = departments[random.Next(departments.Length)]
            });
        }

        return employees.OrderBy(e => e.Name).ToList();
    }

    private void InitializeColumns()
    {
        Columns = new List<UniTableColumn>
        {
            new SmartTableRegularColumn<PersonModel>
            {
                ColumnName = "ID",
                PropertySelector = p => p.Id,
                Width = 60,
                IsFilterable = false,
                IsSortable = true,
                IsReadOnly = true,
                DataType = typeof(int)
            },
            new SmartTableRegularColumn<PersonModel>
            {
                ColumnName = "Name",
                PropertySelector = p => p.Name,
                Width = 150,
                IsFilterable = true,
                IsSortable = true,
                AllowedFilterOperators = new List<FilterOperatorType>
                {
                    FilterOperatorType.Contains,
                    FilterOperatorType.IsEqualTo
                },
                DefaultFilterOperator = FilterOperatorType.Contains,
                DataType = typeof(string)
            },
            new SmartTableRegularColumn<PersonModel>
            {
                ColumnName = "Email",
                PropertySelector = p => p.Email,
                Width = 200,
                IsFilterable = true,
                IsSortable = true,
                AllowedFilterOperators = new List<FilterOperatorType>
                {
                    FilterOperatorType.Contains,
                    FilterOperatorType.IsEqualTo
                },
                DefaultFilterOperator = FilterOperatorType.Contains,
                DataType = typeof(string)
            },
            new SmartTableRegularColumn<PersonModel>
            {
                ColumnName = "Department",
                PropertySelector = p => p.Department,
                Width = 120,
                IsFilterable = true,
                IsSortable = true,
                IsGroupable = true,
                AllowedFilterOperators = new List<FilterOperatorType>
                {
                    FilterOperatorType.IsEqualTo,
                    FilterOperatorType.Contains
                },
                DefaultFilterOperator = FilterOperatorType.IsEqualTo,
                DataType = typeof(string)
            },
            new SmartTableRegularColumn<PersonModel>
            {
                ColumnName = "City",
                PropertySelector = p => p.City,
                Width = 120,
                IsFilterable = true,
                IsSortable = true,
                IsGroupable = true,
                AllowedFilterOperators = new List<FilterOperatorType>
                {
                    FilterOperatorType.IsEqualTo,
                    FilterOperatorType.Contains
                },
                DefaultFilterOperator = FilterOperatorType.IsEqualTo,
                DataType = typeof(string)
            },
            new SmartTableRegularColumn<PersonModel>
            {
                ColumnName = "Age",
                PropertySelector = p => p.Age,
                Width = 70,
                IsFilterable = true,
                IsSortable = true,
                AllowedFilterOperators = new List<FilterOperatorType>
                {
                    FilterOperatorType.Equals,
                    FilterOperatorType.GreaterOrEqual,
                    FilterOperatorType.LessOrEqual
                },
                DefaultFilterOperator = FilterOperatorType.Equals,
                DataType = typeof(int)
            },
            new SmartTableRegularColumn<PersonModel>
            {
                ColumnName = "Salary",
                PropertySelector = p => p.Salary,
                Width = 100,
                IsFilterable = true,
                IsSortable = true,
                AllowedFilterOperators = new List<FilterOperatorType>
                {
                    FilterOperatorType.Equals,
                    FilterOperatorType.GreaterOrEqual,
                    FilterOperatorType.LessOrEqual
                },
                DefaultFilterOperator = FilterOperatorType.GreaterOrEqual,
                DataType = typeof(decimal)
            },
            new SmartTableRegularColumn<PersonModel>
            {
                ColumnName = "Hire Date",
                PropertySelector = p => p.HireDate,
                Width = 110,
                IsFilterable = true,
                IsSortable = true,
                AllowedFilterOperators = new List<FilterOperatorType>
                {
                    FilterOperatorType.Equals,
                    FilterOperatorType.GreaterOrEqual,
                    FilterOperatorType.LessOrEqual
                },
                DefaultFilterOperator = FilterOperatorType.GreaterOrEqual,
                DataType = typeof(DateTime)
            },
            new SmartTableRegularColumn<PersonModel>
            {
                ColumnName = "Active",
                PropertySelector = p => p.IsActive,
                Width = 80,
                IsCheckBox = true,
                IsFilterable = true,
                IsSortable = true,
                AllowedFilterOperators = new List<FilterOperatorType>
                {
                    FilterOperatorType.IsTrue,
                    FilterOperatorType.IsFalse
                },
                DefaultFilterOperator = FilterOperatorType.IsTrue,
                DataType = typeof(bool)
            }
        };
    }

    private void InitializeTableOperations()
    {
        TableOperations = new List<UniTableBaseAction>
        {
            new UniTableAction
            {
                ToolTip = "View Details",
                Command = entity => ViewDetails((PersonModel)entity),
                IconKind = PackIconMaterialKind.Eye
            },
            new UniTableAction
            {
                ToolTip = "Edit Employee",
                Command = entity => EditEmployee((PersonModel)entity),
                IconKind = PackIconMaterialKind.Pencil
            }
        };
    }

    private void ViewDetails(PersonModel employee)
    {
        System.Windows.MessageBox.Show(
            $"Employee Details:\n\n" +
            $"Name: {employee.Name}\n" +
            $"Email: {employee.Email}\n" +
            $"Department: {employee.Department}\n" +
            $"City: {employee.City}\n" +
            $"Age: {employee.Age}\n" +
            $"Salary: {employee.Salary:C0}\n" +
            $"Hire Date: {employee.HireDate:d}\n" +
            $"Status: {(employee.IsActive ? "Active" : "Inactive")}",
            "Employee Information",
            System.Windows.MessageBoxButton.OK,
            System.Windows.MessageBoxImage.Information);
    }

    private void EditEmployee(PersonModel employee)
    {
        System.Windows.MessageBox.Show(
            $"Edit functionality for {employee.Name} would open here.",
            "Edit Employee",
            System.Windows.MessageBoxButton.OK,
            System.Windows.MessageBoxImage.Information);
    }
}

